
import { Project } from './types.ts';

export interface NFTProject extends Project {
  supply: string;
  floor: string;
  chain: string;
}

export const PROJECTS: NFTProject[] = [
  {
    id: '1',
    title: 'NEURAL ECHOES',
    client: 'GENESIS SERIES',
    category: 'Generative AI Art',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2024',
    description: 'An exploration of recursive neural networks visualizing the latent space of human memory. 1000 unique iterations.',
    supply: '1,000',
    floor: '1.2 ETH',
    chain: 'Ethereum'
  },
  {
    id: '2',
    title: 'VOID SCULPTURES',
    client: 'COLLECTIVE VOID',
    category: '3D Abstract',
    imageUrl: 'https://images.unsplash.com/photo-1633167606207-d840b5070fc2?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2024',
    description: 'Bespoke VR-sculpted artifacts existing at the intersection of architecture and digital void.',
    supply: '50',
    floor: '4.5 ETH',
    chain: 'Ethereum'
  },
  {
    id: '3',
    title: 'KINETIC PHANTOMS',
    client: 'PULSE LABS',
    category: 'Motion Design',
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2024',
    description: 'Fluid dynamic simulations representing the pulse of decentralized finance. High-speed kinetic loops.',
    supply: '250',
    floor: '0.8 ETH',
    chain: 'Base'
  },
  {
    id: '4',
    title: 'CYBERNETIC SOUL',
    client: 'AVATAR ARCHIVE',
    category: '3D Portraiture',
    imageUrl: 'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2023',
    description: 'Hyper-realistic digital identities designed for the next generation of spatial computing.',
    supply: '8,888',
    floor: '0.15 ETH',
    chain: 'Ethereum'
  },
  {
    id: '5',
    title: 'CHRONOS DATA',
    client: 'TIMELESS DAO',
    category: 'Glitch / Data Art',
    imageUrl: 'https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2024',
    description: 'Visualizing block-time as physical erosion. Each piece is generated by real-time gas prices at mint.',
    supply: '500',
    floor: '0.5 ETH',
    chain: 'Ethereum'
  },
  {
    id: '6',
    title: 'NEON SYMPHONY',
    client: 'VANTAGE ORIGINALS',
    category: 'Light Painting',
    imageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=1600&h=900',
    year: '2024',
    description: 'Cinematic captures of light trails in virtual cities. A masterclass in digital photon behavior.',
    supply: '100',
    floor: '2.0 ETH',
    chain: 'Solana'
  }
];

export const NAV_LINKS = [
  { label: 'Drops', view: 'work' as const },
  { label: 'Curation', view: 'about' as const },
  { label: 'Artists', view: 'contact' as const }
];
